import FlyonuiScript from "./components/FlyonuiScript";
import "./globals.css";

import {
  Helvetica,
  HelveticaNowDisplay,
  HelveticaNowText,
} from "next/font/google";

const font = Helvetica({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`font-${font.variable} antialiased`}>
        {children}
        <FlyonuiScript />
      </body>
    </html>
  );
}
