import FlyonuiScript from "./components/FlyonuiScript";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-default text-default font-ui">
        {children}
        <FlyonuiScript />
      </body>
    </html>
  );
}
