import FlyonuiScript from "./components/FlyonuiScript";
import "./globals.css";

import "./styles/fonts.css";
const font = { variable: "InterVariable",
};  

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`font-${font.variable} antialiased`}>
        {children}
        <FlyonuiScript />
      </body>
    </html>
  );
}
